;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Combo.Commit",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Window.Close",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Window.Open",DevComment="")
+GameplayTagList=(Tag="Gameplay.Weapons.Sword",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Equip",DevComment="")

